### ISSUE TITLE
Error in module.

### ISSUE THREAD

**Issue by jrviz** [bitfocus/companion-module-generic-tcp-serial#3]
Windows Companion shows "Error: Third argument must be a function" with COM port indicated in Config. Googling this seems to point at an issue with the node-serialport versions. I have tried to use Companion 2.2 to see if the build update is there but get the same issue.

**Comment by rlights** [comment]
+1 for this error, present on anything from 3122 on, but OK on build 3117.
Seems to be this problem: https://github.com/serialport/node-serialport/issues/2191

Suspect it was build 3119 - updating electron to v11.

**Comment by Gartom** [comment]
+1 for this error from me as well, currently on v2.2.0 build 3241. No issue seen on V2.2.0 build 3110.

**Comment by Gartom** [comment]
As far as I understand, a patch for companion has been implemented in https://github.com/bitfocus/companion/commit/65e2c336ce05b942d5098bcb1c3d67e4c2dfe017
