### ISSUE TITLE
Access Denied on Windows 10

### ISSUE THREAD

**Issue by br8kpoint** [bitfocus/companion-module-generic-tcp-serial#4]
Hi I have been trying to connect to a Tenveo VHD202U on Windows 10 (COM5) using the plugin but every time I try it errors out saying Access denied.

Is there something special I have to do to get the plugin to work with this camera?\

I can control the camera via the obs visca plugin so I know the settings are correct but when I restart the computer and try and access the com port via the plugin it gives me the access denied.

**Comment by derrynj** [comment]
@br8kpoint It seems nobody actually answers issues here. But I would suspect an Access denied would be caused by the OBS plugin. Serial ports can only be used by one application at once. So the first app to get access keeps it.

**Comment by istnv** [comment]
FYI this is a volunteer module, submitted in case it may be useful, but it does get used a lot.
Real life does get in the way and sometimes things get overlooked.
Access denied for the serial port suggests another program/service has possession.
@derrynj  is probably correct. If OBS has control, Companion will get errors.
