### ISSUE TITLE
No serial ports detected in 2.3

### ISSUE THREAD

**Issue by derrynj** [bitfocus/companion-module-generic-tcp-serial#5]
I just updated my installation from the latest stable (2.2.3) to the latest Beta [2.3.0+4590-beta-5b925803) and my Generic TCP Serial Port connection doesn't find any serial ports anymore. I've double checked with other software and the COM ports are still active. I should have 3 COM devices (as I did on 2.2.3).
I'm not sure if this is a Companion bug or this module not being compatible anymore as they are still the same module version: 1.0.4.
I've tried wiping the installation and reinstalling fresh with 2.3 and the same thing, I always get the following in the log:

>22.08.11 17:49:25 instance(tsp): No serial ports detected
>22.08.11 17:49:15 instance(tsp): Error initalizing module: SerialPort.list is not a function

That's all it tells me and I can't find any reference to anyone else having this problem..

This is on Windows 10 21H2 64-bit install.

**Comment by istnv** [comment]
Latest serial library API change required updating this module.
