### ISSUE TITLE
No serial ports detected - Ubuntu

### ISSUE THREAD

**Issue by bensteUEM** [bitfocus/companion-module-generic-tcp-serial#8]
I do get a "No serial ports detected" error on Ubuntu.
Assuming companion is running as my local user (which is part of the dialout) group it should have detected /dev/ttyUSB0
I've been successfully using the port with Node.js therefore this seems to be an isssue with companion?

**Comment by Xcodo** [comment]
Are you using Companion 2.3.0? If so the issue is documented in #5 and fixed. Options are to downgrade to a previous version or use a recent beta.

**Comment by bensteUEM** [comment]
@Xcodo thanks for pointing me to the other bug - sorry for not realizing the duplication earlier.
I can confirm companion-x64-2.3.0+4667-beta does show the serial port ... it is indeed a duplicate of #5
